;Inscription d'un nouveau membre: donnees generales
[general]
nom=Antenne
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5

;dynamique
;tables dynamiques sont celles qui stocquent les champs oblig et facul ci-dessous
;tables[0] contient la PK
;PK la cle primaire principale de tables[0] est la clé du  contexte. Elle  sera retournée en valeur finale
;FK la cle auxiliaire de tables[1] pointe sur PK
[dynamique]
tables=spip_vap_antenne
PK=idant

;cles extra : si la table possède une ou des Foreign Keys
;si plusieurs, l'odre vertical doit etre respecté table[0], FK[0], FKP[0] etc
[extra]
tables=spip_vap_regions
FK=lienreg
FKP=idreg

;passive : les valeurs des 'champs' sont selectionnees dans 'tables' via 'PK' et fournies en supplement au contexte
;permet la creation d'un cache de donnee 'passives' à servir à chaque fois dans ce contexte
;pas de FK ici
[passive]
tables=spip_vap_regions
PK=idreg
champs=idreg,nomregion,province
 
;formulaires obligatoires et facultatifs par statut
[anonym]
oblig=nomantenne,lienreg
[membre]
oblig=nomantenne,lienreg
[responsable]
oblig=nomantenne,lienreg
vue=nomantenne,lienreg 
[admin]
oblig=nomantenne,lienreg 
vue=nomantenne,lienreg
