;donnees generales: nom du contexte, action (semble obsolete)
[general]
nom=Authentification
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5

;dynamique: les tables 'dynamiques' sont celles qui stocquent les champs oblig et facul ci-dessous
;tables[0] doit contenir la PK qui est la Principal Primary Key du contexte
;PK la Primary Key, PK[0] doit etre la PK de tables[0] et est la PPK du  contexte. Elle  sera retournée en valeur finale
;FK la cle auxiliaire de tables[1], doit pointer(Foreign Key Pointe) sur PK[0]
[dynamique]
tables=spip_vap_humains 
PK=idhum 

; spip_vap_humains possede une FK lienreg qui pointe sur idreg
[extra]
tables=spip_vap_regions
FK=lienreg
FKP=idreg
  
;formulaires obligatoires et facultatifs par statut
;il serait judicieux d'ordonner les donnees de admin comme pour les select de l'ancien vapilote_sortie
[anonym]
oblig=mail,passe 
vue=nom,passe
[membre]
oblig=mail,passe 
vue=nom,passe
[responsable]
oblig=mail,passe 
vue=nom,passe
[admin]
oblig=mail,passe 
vue=nom,passe


; les appels de requetes sql pour l'affichage general d'un contexte devraient passer par une classe statique...à preciser...

