;Inscription d'un nouveau membre: donnees generales
[general]
nom=Chat
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5
  
[dynamique]
tables=spip_vap_chat
PK=idchat

[extra]
tables=spip_vap_humains,spip_vap_antenne
FK=lienhum,lienant
FKP=idhum,idant
 
[passive]
tables=spip_vap_antenne
PK=idant
champs=idant,nomantenne,lienreg

;formulaires obligatoires et facultatifs par statut
[anonym]
oblig=lienant,pseudo,vapattache,vaputile,message,sujet,idpere,lienhum,chatmail
facul=poste
[membre]
oblig=lienant,lienhum,pseudo,vapattache,vaputile,message,sujet,idpere,chatmail
facul=poste
vue=sujet,message,poste
[responsable]
oblig=lienant,lienhum,pseudo,vapattache,vaputile,message,sujet,idpere,chatmail
facul=poste
vue=sujet,message,poste
[admin]
oblig=lienant,lienhum,pseudo,vapattache,vaputile,message,sujet,idpere,chatmail
facul=poste
vue=sujet,message,poste
