;Inscription d'un nouveau membre: donnees generales
[general]
nom=File
action=insertion
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5
 
;dynamique
;tables dynamiques sont celles qui stocquent les champs oblig et facul ci-dessous
;tables[0] contient la PK
;PK la cle primaire principale de tables[0] est la clé du  contexte. Elle  sera retournée en valeur finale
;FK la cle auxiliaire de tables[1] pointe sur PK
[dynamique]
tables=spip_vap_files
PK=idFile

[passive]
tables=spip_vap_antenne
PK=idant
champs=idant,nomantenne,lienreg
 
;formulaires obligatoires et facultatifs par statut
[responsable]
oblig=nomFile
facul=descFile,pathFile,sizeFile,dateFile
[admin]
oblig=nomFile
facul=descFile,pathFile,sizeFile,dateFile 
