;donnees generales: nom du contexte, action (semble obsolete)
[general]
nom=Help
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5

;ATTENTION!! ce contexte utilise la meme table que contexte Membre, 
;il doit en reprendre les memes caracteristiques de clé (pour cette table ci)!!
;car ces deux contextes vont se partager le meme fichier tables/spip_vap_humains.ini
[dynamique]
tables=spip_vap_humains
PK=idhum

; spip_vap_humains possede une FK lienreg qui pointe sur idreg
[extra]
tables=spip_vap_regions
FK=lienreg
FKP=idreg

; facul est ici une astuce pour utiliser le modele en mise à jour du passe
[anonym]
oblig=nom,prenom,mail
facul=passe
[membre]
oblig=nom,prenom,mail
facul=passe
[responsable]
oblig=nom,prenom,mail
facul=passe
[admin]
oblig=nom,prenom,mail
facul=passe

