 
[general]
nom=News
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5
[dynamique]
tables=spip_vap_news
PK=idnews

[passive]
tables=spip_vap_antenne
PK=idant
champs=idant,nomantenne,lienreg


;formulaires obligatoires et facultatifs par statut
 
[responsable]
oblig=sujet,contenu,expediteur
facul=altcontenu,couleurfond,couleurpolice,couleurtitre 
vue=expediteur,sujet,contenu,couleurfond,couleurpolice,couleurtitre
[admin]
oblig=sujet,contenu,expediteur
facul=altcontenu,couleurfond,couleurpolice,couleurtitre
vue=expediteur,sujet,contenu,couleurfond,couleurpolice,couleurtitre 

