;Inscription d'un nouveau membre: donnees generales
[general]
nom=Region
action=insertion
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5

[dynamique]
tables=spip_vap_regions
PK=idreg
 
;formulaires obligatoires et facultatifs par statut
[anonym]
oblig=nomregion,province
[membre]
oblig=nomregion,province
[responsable]
oblig=nomregion,province
vue=nomregion,province
[admin]
oblig=nomregion,province 
vue=nomregion,province
