;Inscription d'un nouveau membre: donnees generales
[general]
nom=Trajet
mail=info@vap-vap.be
horsAntenne=19
horsRegion=5

;dynamique
;tables dynamiques sont celles qui stocquent les champs oblig et facul ci-dessous
;tables[0] contient la PK
;PK la cle primaire principale de tables[0] est la clé du  contexte. Elle  sera retournée en valeur finale
;FK la cle auxiliaire de tables[1] pointe sur PK
[dynamique]
tables=spip_vap_trajet
PK=idtraj
 
;cles extra : si la table possède une ou des Foreign Keys
;si plusieurs, l'odre vertical doit etre respecté table[0], FK[0], FKP[0] etc
[extra]
tables=spip_vap_humains,spip_vap_passage,spip_vap_antenne
FK=lienhum,lienpass,lienant
FKP=idhum,idpass,idant
 
;formulaires obligatoires et facultatifs par statut
[anonym]
oblig=commune,deal
facul=lienpass,lienhum,destination,periode,poste
[membre]
oblig=commune,deal
facul=lienpass,lienhum,lienant,destination,periode,poste
vue=commune,destination,periode 
[responsable]
oblig=commune,deal
facul=lienpass,lienhum,lienant,destination,periode,poste
vue=commune,destination,periode
[admin]
oblig=commune,deal
facul=lienpass,lienhum,lienant,destination,periode,poste
vue=commune,destination,periode
